package seng201.team0.models.items;

/**
 * Represents an Ammo Crate item which provides bonus resources generated by ammunition towers.
 */
public class AmmoCrate extends Item {

    /**
     * Constructs an Ammo Crate with a predefined name and cost.
     */
    public AmmoCrate() {
        super("Ammo Crate", 350, false);
    }

    /**
     * Gets the type of tower that this item affects.
     *
     * @return The type of tower that this item affects, which is "Ammunition".
     */
    public String getTowerType() {
        return "Ammunition";
    }

    /**
     * Gets the description of this item.
     *
     * @return The description of this item.
     */
    public String getDescription() {
        return "A crate of ammunition which provides\nbonus resources generates by ammunition towers.";
    }


}
