package seng201.team0.models.items;

public class MedicalSupplyDrop extends Item {
    public MedicalSupplyDrop() {
        super("Medical Supply Drop", 500, false);
    }

    public String getTowerType() {
        return "Medkits";
    }

    public String getDescription() {
        return "An ariel supply drop that provides\n bonus resources generated by medkit towers.";
    }
}
