package seng201.team0.models.items;

/**
 * Represents a paratrooper item which provides bonus resources generated by troop towers.
 */
public class Paratroopers extends Item {

    /**
     * Constructs a paratrooper item with a predefined name and cost.
     */
    public Paratroopers() {
        super("Paratroopers", 650, false);
    }

    /**
     * Gets the type of tower that this item affects.
     *
     * @return The type of tower that this item affects, which is "Troops".
     */
    public String getTowerType() {
        return "Troops";
    }

    /**
     * Gets the description of this item.
     *
     * @return The description of this item.
     */
    public String getDescription() {
        return "A platoon of paratroopers which provide\nbonus resources generated by troop towers.";
    }
}
